export const English = {
    // 言語
    LANGUAGE: 'English',

    // ボタン・タグ
    PLAYER_NAME: "Player Name",
    QUICK_MATCH: "Quick Match",
    FRIEND_MATCH: "Play with Friends",
    LANG_EN: "English",
    LANG_JP: "Japanese",
    LANG_CN: "Chinese",
    TUTORIAL: "Tutorial",
    INTRODUCTION: "What is NumBuyer?",
    CAPTION: "Game Flow",
    TIME_LINE1: "Before Game",
    TIME_LINE2: "Distribution and Publication",
    TIME_LINE3: "Auction",
    TIME_LINE4: "Calculation",
    TIME_LINE5: 'End of game',
    CREATE_BTN: "Create",
    JOIN_BTN: "Join",
    ROOM_ID: "Room ID",
    ABILITY: "Please select two abilities.",
    ABILITY_EXP1: "Abilities are special abilities that can be activated during the game.",
    ABILITY_EXP2: "There are active abilities that can be used only a limited number of times and skipive abilities that are always in effect.",
    BST_TYPE: 'Boost Type',
    ATK_TYPE: 'Attack Type',
    RCV_TYPE: 'Recover Type',
    JAM_TYPE: 'Jamming Type',
    CNF_TYPE: 'Confusion Type',
    LOBBY: 'Lobby',
    SETTING: 'Settings',
    MULTIPLICATION: 'Multiplication',
    DIVISION: 'Division',
    LIMIT: 'Limit of Number',
    START_BTN: 'Start',
    BACK_BTN: 'Back',
    TARGET: 'Target Card',
    AUCTION: 'Auction Cards',
    BID_MSG: 'Please enter the bid amount',
    BID_BTN: 'Bid',
    SUCCESS_BID: 'Successful bid!',
    PASS_BTN: 'Skip',
    ANSWER_BTN: 'Answer',
    ABILITY_TAG: 'Use Abilities',
    YOUR_CARDS: 'Your Cards',
    CALCULATE_FIELD: 'Calculate Field',
    YES_BTN: 'Yes',
    NO_BTN: 'No',
    SUCCESS: 'SUCCESS!',
    FAILED: 'FAILED…!',
    CONFIRM_BTN: 'Done',
    TIME: 'Time',
    WIN_CONDITIONS: 'Win conditions',
    WIN_MSG: 'Have',
    COIN: 'Coin',
    RANKING: 'RANKING',
    FINISH_BTN: 'Finish Game',
    AGAIN_BTN: 'Play Again',

    // チュートリアルメッセージ
    INTRODUCTION_MSG1: "NumBuyer is a title born from the two words Number and Buyer, and as the name implies, it is a new type of card game that combines a calculation card game with an auction element.",
    INTRODUCTION_MSG2: "Game rules",
    INTRODUCTION_MSG3: "First, two types of cards, numbers and operators, are dealt.",
    INTRODUCTION_MSG4: "After that, a Target card with numbers will be released. You can earn coins by combining the cards you have to make the number of Target card.",
    INTRODUCTION_MSG5: "The first person to collect the amount of coins presented as a victory condition is the winner of this game!",
    INTRODUCTION_MSG6: "One card will be dealt each turn, but that alone will not be enough to make the number of Target card. Therefore, the Auction card will be released after the Target card is released.",
    INTRODUCTION_MSG7: "This Auction card can be obtained in an auction format using your coins.",
    INTRODUCTION_MSG8: "Let's make good use of Auction cards and efficiently create numbers for Target card!",
    INTRODUCTION_MSG9: "After the end of the auction phase, the calculation phase comes. Let's make a calculation formula so that the number of the Target card will be the calculation result with the card you have. (Of course, you can use only one card that has exactly the same number as the Target card)",
    INTRODUCTION_MSG10: "If you can make the numbers of the Target card brilliantly, you will get coins for the value of the Target card and the number of cards you used! (You will get bonus coins according to the number of cards you used!)",
    INTRODUCTION_MSG11: "After that, let's just repeat this series of steps and collect a lot of coins faster than anyone else!",
    BEFORE_GAME_MSG1: "To start the game",
    BEFORE_GAME_MSG2: "①You can change to your favorite language by pressing here.",
    BEFORE_GAME_MSG3: "②Enter the name of your player you want to use in the game.",
    BEFORE_GAME_MSG4: '③If you press "Quick Match", you can play against 4 random players from all over the world.',
    BEFORE_GAME_MSG5: '④If you press "Play with Friends", you can play 2-4 people with an acquaintance by sharing the room code.',
    BEFORE_GAME_MSG6: "Select abilities",
    BEFORE_GAME_MSG7: "①Select the two abilities you want to use from the five types of abilities.",
    BEFORE_GAME_MSG8: '②After selecting an ability, press "Done" to proceed to the next screen.',
    BEFORE_GAME_MSG9: 'Create or enter a room (in the case of "Play with Friends")',
    BEFORE_GAME_MSG10: "①Create a new room to play the game.",
    BEFORE_GAME_MSG11: "②Ask the room owner to tell you the room code and enter it.",
    BEFORE_GAME_MSG12: "③Enter the room with the room code you entered.",
    BEFORE_GAME_MSG13: 'Lobby (in the case of "Play with Friends")',
    BEFORE_GAME_MSG14: "The participants in the room are displayed. (There is an icon next to the room owner)",
    BEFORE_GAME_MSG15: "①You can press here to leave the room and return to the title screen.",
    BEFORE_GAME_MSG16: "②Press here to copy the room code for this room. (Tell your friends who want to join this room code)",
    BEFORE_GAME_MSG17: "③When the room has 2-4 participants, the room creator can press here to start the game.",
    BEFORE_GAME_MSG18: 'Lobby (in the case of "Quick Match")',
    BEFORE_GAME_MSG19: "The participants in the room are displayed. ",
    BEFORE_GAME_MSG20: "The game starts when there are 4 participants in the room.",
    DISTRIBUTION_MSG1: "Start the game",
    DISTRIBUTION_MSG2: "①The victory conditions of the game are written here. Collecting 100 coins is the winning condition for this game.",
    DISTRIBUTION_MSG3: "②You can check the player information. The player name, the number of cards in your hand, and the coins you have are listed. (Yellow background is my information)",
    DISTRIBUTION_MSG4: "③You can check your abilities. You can also see a description of each ability by focusing on it. You cannot see your opponent's abilities. (You can check only the timing when the other party is activated)",
    DISTRIBUTION_MSG5: "Hand distribution",
    DISTRIBUTION_MSG6: "①Here you will see a description of the game situation and how to perform each action.",
    DISTRIBUTION_MSG7: "②First, two types of cards, numbers and operators, are dealt.",
    DISTRIBUTION_MSG8: "Publication of Target Card",
    DISTRIBUTION_MSG9: 'Target Card with numbers will be released. You can earn coins by combining your hands and making this number.',
    AUCTION_PHASE_MSG1: "Publication of Auction Card",
    AUCTION_PHASE_MSG2: "After the Target Card is released, Auction Card will be released. In this Auction Phase, an auction will be held for all players and this Auction Card will be added to the hand of the winning bidder.",
    AUCTION_PHASE_MSG3: "Bid or decline",
    AUCTION_PHASE_MSG4: "①The time remaining until the end of the auction is displayed here. When the remaining time reaches 0, the card will be awarded to the player who bids the highest bid at that time.",
    AUCTION_PHASE_MSG5: '②You can decline the auction this turn by pressing the "Skip" button.',
    AUCTION_PHASE_MSG6: '③Rewrite this number as it is, or press the "+" button or "-" button to set the bid amount.',
    AUCTION_PHASE_MSG7: '④You can bid at the set bid amount by pressing the "Bid" button.',
    AUCTION_PHASE_MSG8: "Current highest bid",
    AUCTION_PHASE_MSG9: "The current highest bid will be displayed when someone bids. You cannot bid below the maximum bid.",
    AUCTION_PHASE_MSG10: "Successful bid",
    AUCTION_PHASE_MSG11: "If you make a successful bid, the effect will be displayed like this, and the winning card will be added to your hand.",
    CALCULATION_PHASE_MSG1: "Choosing the card to use for the calculation or Skip",
    CALCULATION_PHASE_MSG2: "①Select the card in your hand so that the target card is the calculation result. You cannot select number cards in succession. Be sure to insert the code card.",
    CALCULATION_PHASE_MSG3: '②You can pass the calculation for this turn by pressing the "Skip" button.',
    CALCULATION_PHASE_MSG4: "Answer",
    CALCULATION_PHASE_MSG5: 'Press the "Answer" button and answer using the formula consisting of the selected cards.',
    CALCULATION_PHASE_MSG6: "Incorrect answer",
    CALCULATION_PHASE_MSG7: "If the answer is incorrect, the card used for the answer will be returned to your hand again. You can answer as many times as you like within the time limit.",
    CALCULATION_PHASE_MSG8: "Correct answer",
    CALCULATION_PHASE_MSG9: "If you answer correctly, you will get the number of target cards and coins for the number of cards used for the answer. The card used for the answer will be lost.",
    CALCULATION_PHASE_MSG10: 'Repeat the above steps of "Distribution of hand"→"Publication of target card"→"Publication of auction card"→"Auction"→"Answer" and proceed with the game so that the number of coins you have is the number of winning conditions. I will continue.',
    USE_ABILITIES_MSG1: "Possession abilities",
    USE_ABILITIES_MSG2: "①You can check your abilities in the player information on the right side, and when you focus on them, the effects of the abilities will be displayed.",
    USE_ABILITIES_MSG3: "②Active Abilities that can be used at any time can be activated by pressing the button here.",
    USE_ABILITIES_MSG4: "Use of Active Abilities",
    USE_ABILITIES_MSG5: "Focus on the button to see the effect of the ability. You can activate the ability by pressing the button.",
    USE_ABILITIES_MSG6: "Activate abilities",
    USE_ABILITIES_MSG7: "①When an ability is activated, a message will be displayed as to who activated what ability and what effect it had.",
    USE_ABILITIES_MSG8: "②Only when the ability is activated, the ability of the activated player is displayed.",
    USE_ABILITIES_MSG9: "Activate passive abilities",
    USE_ABILITIES_MSG10: "Passive abilities are automatically activated when certain conditions stated in the effect are met.",
    END_GAME_MSG1: "Final result of the game",
    END_GAME_MSG2: "①The final result of the game is displayed in a ranking format.",
    END_GAME_MSG3: "②Press this button to exit the room and return to the title screen.",

    // エラーメッセージ
    NULL_NAME_ERR: "Please enter your name.", // 名前が未入力
    SYMBOL_ERR: "You cannot enter that character.", // 禁止文字が入力されている
    NULL_ROOM_ID_ERR: "Please enter Room ID.", // ルームが未入力
    LENGTH_ROOM_ID_ERR: 'Please enter the room ID in 10 digits.', // ルームIDが10桁以外
    NOT_EXIST_ROOM_ERR: 'This room ID does not exist.', // 存在しないルームID
    ABILITY_ERR: 'Please select two abilities.', // アビリティを2つ選択していない
    NULL_BID_ERR: "Please enter the amount.", // 金額が未入力
    NUM_ERR: "You can only enter numbers.", // 数字以外が入力されている
    BID_ERR: "Please enter an amount higher than the highest bid.", // 最高入札額以下の金額が入力されている
    LACK_ERR: "You don't have enough money.", // 所持金が足りない
    DOUBLE_ERR: "You cannot bid twice in a row.", // ２回連続入札
    BAD_TIMING_ABILITY_AUC_ERR: "This ability cannot be used during the auction phase.", // オークションフェーズに発動できないアビリティ
    NOT_MEET_ABILITY_3TURN_ERR: "This ability cannot be activated for 3 turns from the start of the game.", // 最初の3ターン発動できないアビリティ


    // ナビゲーションメッセージ
    QUICK_MSG: 'The game will start automatically when all four players are together.',
    GIVE_CARD_MSG: 'Distributing cards to players...',
    SHOW_TAR_MSG: 'The target card is ',
    SHOW_AUC_MSG: ' was exhibited',
    AUCTION_MSG1: "Please enter the bid amount and select whether to bid for ' ",
    AUCTION_MSG2: " ' or skip.",
    AUC_BID_MSG1: ' bid for ',
    AUC_BID_MSG2: ' coin.',
    AUC_HIGHEST_MSG1: 'Current highest bid: ',
    AUC_HIGHEST_MSG2: 'coin ( ',
    AUC_HIGHEST_MSG3: ' )',
    AUC_RESULT_MSG0: 'No one bid.',
    AUC_RESULT_MSG1: " made a successful bid for ' ",
    AUC_RESULT_MSG2: " ' with ",
    AUC_RESULT_MSG3: ' coin! ',
    CALCULATE_MSG1: "Select from your cards so that the calculation result is ' ",
    CALCULATE_MSG2: " ' and press 'ANSWER'.",
    CALC_ERR_MSG1: 'Please select your Cards!',
    CALC_ERR_MSG2: 'Code is at the end!',
    CALC_RESULT_MSG0: 'Incorrect...! Calc again or skip.',
    CALC_RESULT_MSG1: 'Correct!! One card will be given! Please wait for other players...',
    CALC_FINISH_MSG0: 'There was no one giving correct answer...',
    CALC_FINISH_MSG1: 'It was ',
    CALC_FINISH_MSG2: ' who gave the correct answer! ',
    CALC_FINISH_MSG3_1: ' get ',
    CALC_FINISH_MSG3_2: ' coin(card number bonus : ',
    CALC_FINISH_MSG3_3: ' coin) and one card! ',
    PASS_TITLE: 'Are you sure you want to skip?',
    PASS_MSG: "If you want to skip, press the 'YES'",
    ABILITY_TITLE: "Do you really use it?",
    ABILITY_MSG: "If you want to use, press the 'YES'",
    FIRED_ABILITY_MSG1: " activates '",
    FIRED_ABILITY_MSG2: "'!",

}

export const Japanese = {
    // 言語
    LANGUAGE: 'Japanese',

    // ボタン・タグ
    PLAYER_NAME: 'プレイヤー名',
    QUICK_MATCH: '誰かと対戦する',
    FRIEND_MATCH: '友達と対戦する',
    LANG_EN: '英語',
    LANG_JP: '日本語',
    LANG_CN: '中国語',
    TUTORIAL: 'チュートリアル',
    INTRODUCTION: 'NumBuyerとは',
    CAPTION: 'ゲームの流れ',
    TIME_LINE1: 'ゲームを始めるまで',
    TIME_LINE2: 'カードの配布と公開',
    TIME_LINE3: 'オークション',
    TIME_LINE4: '計算',
    TIME_LINE5: 'ゲームの終了',
    CREATE_BTN: '部屋を作る',
    JOIN_BTN: '部屋に参加する',
    ROOM_ID: 'ルームID',
    ABILITY: 'アビリティを2つ選択してください。',
    ABILITY_EXP1: "アビリティはゲーム中に発動できる特殊能力です。",
    ABILITY_EXP2: "使用回数の限られているアクティブアビリティと常に効果が発動しているパッシブアビリティがあります。",
    BST_TYPE: '速攻タイプ',
    ATK_TYPE: '攻撃タイプ',
    RCV_TYPE: '回復タイプ',
    JAM_TYPE: '妨害タイプ',
    CNF_TYPE: '混乱タイプ',
    LOBBY: 'ロビー',
    SETTING: '各種設定',
    MULTIPLICATION: '掛け算',
    DIVISION: '割り算',
    LIMIT: '数字の上限',
    START_BTN: 'スタート',
    BACK_BTN: '退出する',
    TARGET: '目標カード',
    AUCTION: 'オークションカード',
    BID_MSG: '入札金額を入力してください。',
    BID_BTN: '入札',
    SUCCESS_BID: '落札成功！',
    PASS_BTN: 'パス',
    ANSWER_BTN: '解答',
    ABILITY_TAG: 'アビリティを使う',
    YOUR_CARDS: 'あなたの手札',
    CALCULATE_FIELD: '計算フィールド',
    YES_BTN: 'はい',
    NO_BTN: 'いいえ',
    SUCCESS: '正解！',
    FAILED: '不正解…！',
    CONFIRM_BTN: '確定',
    TIME: '残り時間',
    WIN_CONDITIONS: '勝利条件',
    WIN_MSG: 'を集める',
    COIN: 'コイン',
    RANKING: 'ランキング',
    FINISH_BTN: 'ゲームをやめる',
    AGAIN_BTN: 'もう一度プレイする',

    // チュートリアルメッセージ
    INTRODUCTION_MSG1: 'NumBuyerとはNumber(数字)とBuyer(買い手)の二つの単語から生まれたタイトルであり、その名の通り計算カードゲームにオークション要素を組み合わせた新感覚のカードゲームです。',
    INTRODUCTION_MSG2: 'ゲームのルール',
    INTRODUCTION_MSG3: '最初に数字と演算子の２種類のカードが配られます。',
    INTRODUCTION_MSG4: 'その後、数字が書かれた「目標カード」が公開されます。手持ちのカードを組み合わせて「目標カード」の数字を作るとコインを獲得できます。',
    INTRODUCTION_MSG5: '勝利条件として提示された額のコインを一番最初に集めた人がこのゲームの勝者です!',
    INTRODUCTION_MSG6: '毎ターン１枚ずつカードは配られますが、それだけでは「目標カード」の数字を作るまでの道のりが程遠いでしょう。したがって「目標カード」の公開後に「オークションカード」が公開されます。',
    INTRODUCTION_MSG7: 'この「オークションカード」は手持ちのコインを使ってオークション形式で入手することができます。',
    INTRODUCTION_MSG8: '「オークションカード」をうまく活用して「目標カード」の数字を効率良く作りましょう!',
    INTRODUCTION_MSG9: 'オークションフェーズの終了後、計算フェーズがやってきます。手持ちのカードで「目標カード」の数字が計算結果となるように計算式を作りましょう。(もちろん「目標カード」の数字と全く同じカードを１枚だけ使っても良いです)',
    INTRODUCTION_MSG10: '「目標カード」の数字を見事作ることができれば「目標カード」の値と使用した手札の枚数分のコインがもらえます!(使ったカードの枚数に応じて、ボーナスコインがもらえます!)',
    INTRODUCTION_MSG11: '後はひたすらこの一連の流れを繰り返してコインを誰よりも早くたくさん集めましょう!',
    BEFORE_GAME_MSG1: "ゲームを始めるために",
    BEFORE_GAME_MSG2: "①ここを押すと好きな言語に変更できます。",
    BEFORE_GAME_MSG3: "②ゲームで使用したい自身のプレイヤー名を入力してください。",
    BEFORE_GAME_MSG4: "③「誰かと対戦する」を押すと、世界中のランダムなプレイヤーと４人対戦できます。",
    BEFORE_GAME_MSG5: "④「友達と対戦する」を押すと、ルームコードを共有することで知り合いと２〜４人対戦できます。",
    BEFORE_GAME_MSG6: "アビリティを選択する",
    BEFORE_GAME_MSG7: "①５つのタイプのアビリティから使用したいアビリティを２つ選択します。",
    BEFORE_GAME_MSG8: "②アビリティを選択したら「確定」を押すと次の画面に進みます。",
    BEFORE_GAME_MSG9: "ルームを作成または入室する（「友達と対戦する」の場合）",
    BEFORE_GAME_MSG10: "①新たにゲームをプレイするルームを作ります。",
    BEFORE_GAME_MSG11: "②ルームの作成者からルームコードを教えてもらい、ルームコードを入力してください。",
    BEFORE_GAME_MSG12: "③入力したルームコードのルームに入室します。",
    BEFORE_GAME_MSG13: "ロビー（「友達と対戦する」の場合）",
    BEFORE_GAME_MSG14: "ルームの参加者が表示されます。（ルームの作成者の横にはアイコンが付きます）",
    BEFORE_GAME_MSG15: "①ここを押すとルームを退場してタイトル画面に戻ることができます。",
    BEFORE_GAME_MSG16: "②ここを押すと、このルームのルームコードをコピーできます。（このルームコードを参加させたい友達に教えてください）",
    BEFORE_GAME_MSG17: "③ルームの参加者が２〜４人になると、ルームの作成者はここを押してゲームを開始できます。",
    BEFORE_GAME_MSG18: "ロビー（「誰かと対戦する」の場合）",
    BEFORE_GAME_MSG19: "ルームの参加者が表示されます。",
    BEFORE_GAME_MSG20: "ルームの参加者が４人になると、ゲームが開始されます。",
    DISTRIBUTION_MSG1: "ゲームの開始",
    DISTRIBUTION_MSG2: "①ここにゲームの勝利条件が書かれています。１００コインを集めることがこのゲームの勝利条件です。",
    DISTRIBUTION_MSG3: "②プレイヤーの情報を確認できます。プレイヤー名、手札の枚数、所持コインが載っています。（黄色背景が自分の情報）",
    DISTRIBUTION_MSG4: "③所持アビリティを確認できます。フォーカスを当てるとそれぞれの能力の説明も確認できます。相手の所持アビリティは見えません。（相手が発動したタイミングのみ確認できます）",
    DISTRIBUTION_MSG5: "手札の配布",
    DISTRIBUTION_MSG6: "①ここにゲームの状況と各アクションの実行方法などの説明が表示されます。",
    DISTRIBUTION_MSG7: "②最初に数字と演算子の２種類のカードが配られます。",
    DISTRIBUTION_MSG8: "目標カードの公開",
    DISTRIBUTION_MSG9: "数字が書かれた「目標カード」が公開されます。手札を組み合わせてこの数字を作るとコインを獲得できます。",
    AUCTION_PHASE_MSG1: "オークションカードの公開",
    AUCTION_PHASE_MSG2: "目標カードの公開後、オークションカードが公開されます。このオークションフェーズでは全プレイヤーでオークションが開かれ、落札した人の手札にこのオークションカードが加わります。",
    AUCTION_PHASE_MSG3: "入札または辞退",
    AUCTION_PHASE_MSG4: "①オークション終了までの残り時間がこちらに表示されます。残り時間が0になるとその時点での最高額を入札したプレイヤーにカードが落札されます。",
    AUCTION_PHASE_MSG5: "②「パス」ボタンを押すとこのターンのオークションを辞退できます。",
    AUCTION_PHASE_MSG6: "③こちらの数字をそのまま書き換えるか「＋」ボタンか「ー」ボタンを押して入札金額を設定します。",
    AUCTION_PHASE_MSG7: "④「入札」ボタンを押すと設定した入札金額で入札できます。",
    AUCTION_PHASE_MSG8: "現在の最高入札額",
    AUCTION_PHASE_MSG9: "誰かが入札したタイミングで現在の最高入札額が表示されます。最高入札額以下の金額では入札できません。",
    AUCTION_PHASE_MSG10: "落札",
    AUCTION_PHASE_MSG11: "落札に成功するとこのようにエフェクトが表示され、手札に落札したカードが追加されます。",
    CALCULATION_PHASE_MSG1: "計算に使用するカードの選択またはパス",
    CALCULATION_PHASE_MSG2: "①目標カードが計算結果になるように手札のカードを選択します。数字カードを連続して選択することはできません。必ず符号カードを挟みましょう。",
    CALCULATION_PHASE_MSG3: "②「パス」ボタンを押すと、このターンの計算をパスできます。",
    CALCULATION_PHASE_MSG4: "解答",
    CALCULATION_PHASE_MSG5: "「解答」ボタンを押して選択されているカードで構成された計算式で解答します。",
    CALCULATION_PHASE_MSG6: "不正解",
    CALCULATION_PHASE_MSG7: "不正解だった場合、解答に使用したカードは再び手札に戻ります。時間内であれば何度でも解答できます。",
    CALCULATION_PHASE_MSG8: "正解",
    CALCULATION_PHASE_MSG9: "正解した場合、目標カードの数値と解答に使用したカードの枚数分のコインを獲得します。解答に使用したカードは失われます。",
    CALCULATION_PHASE_MSG10: "以上の「手札の配布」→「目標カードの公開」→「オークションカードの公開」→「オークション」→「解答」という流れを繰り返していき、所持コインが勝利条件の枚数になるようにゲームを進めていきます。",
    USE_ABILITIES_MSG1: "所持アビリティ",
    USE_ABILITIES_MSG2: "①自分の所持アビリティは右側のプレイヤー情報で確認でき、フォーカスを当てるとアビリティの効果が表示されます。",
    USE_ABILITIES_MSG3: "②好きなタイミングで使用できるアクティブアビリティはここのボタンを押すことで発動できます。",
    USE_ABILITIES_MSG4: "アクティブアビリティの使用",
    USE_ABILITIES_MSG5: "ボタンにフォーカスを当てるとアビリティの効果が表示されます。ボタンを押すとアビリティを発動できます。",
    USE_ABILITIES_MSG6: "アビリティの発動",
    USE_ABILITIES_MSG7: "①アビリティが発動されると、誰が何のアビリティを発動しどのような効果をもたらしたかのメッセージが表示されます。",
    USE_ABILITIES_MSG8: "②アビリティが発動したタイミングだけ、発動したプレイヤーのアビリティが表示されます。",
    USE_ABILITIES_MSG9: "パッシブアビリティの発動",
    USE_ABILITIES_MSG10: "パッシブアビリティは効果に書いてある特定の条件を満たすと自動で発動されます。",
    END_GAME_MSG1: "ゲームの最終結果",
    END_GAME_MSG2: "①ゲームの最終結果がランキング形式で表示されます。",
    END_GAME_MSG3: "②このボタンを押すと、ルームを抜けてタイトル画面に戻ります。",

    // エラーメッセージ
    NULL_NAME_ERR: '名前を入力してください。', // 名前が未入力
    SYMBOL_ERR: 'その文字は入力できません。', // 禁止文字が入力されている
    NULL_ROOM_ID_ERR: 'ルームIDを入力してください。', // ルームIDが未入力
    LENGTH_ROOM_ID_ERR: 'ルームIDは１０桁で入力してください。', // ルームIDが10桁以外
    NOT_EXIST_ROOM_ERR: '存在しないルームIDです。', // 存在しないルームID
    ABILITY_ERR: 'アビリティを２つ選択してください。', // アビリティを2つ選択していない
    NULL_BID_ERR: '金額を入力してください。', // 金額が未入力
    NUM_ERR: '数字を入力してください。', // 数字以外が入力されている
    BID_ERR: '最高入札額より高い金額を入力してください。', // 最高入札額以下の金額が入力されている
    LACK_ERR: "所持金が足りません。", // 所持金が足りない
    DOUBLE_ERR: "２回続けて入札はできません。", // ２回連続入札
    BAD_TIMING_ABILITY_AUC_ERR: "このアビリティはオークションフェーズに使用できません。", // オークションフェーズに発動できないアビリティ
    NOT_MEET_ABILITY_3TURN_ERR: "このアビリティはゲーム開始から3ターンの間は発動できません。", // 最初の3ターン発動できないアビリティ

    // ナビゲーションメッセージ
    QUICK_MSG: '４人揃うと自動でゲームが始まります。',
    GIVE_CARD_MSG: 'カードを配布しています…',
    SHOW_TAR_MSG1: '目標カードは ',
    SHOW_TAR_MSG2: ' です。',
    SHOW_AUC_MSG: ' が出品されました。',
    AUCTION_MSG1: '入札金額を入力し、 ',
    AUCTION_MSG2: ' に入札するかパスするかを選択してください。',
    AUC_BID_MSG1: ' が ',
    AUC_BID_MSG2: 'コインで入札しました。',
    AUC_HIGHEST_MSG1: '現在の最高入札額: ',
    AUC_HIGHEST_MSG2: 'コイン ( ',
    AUC_HIGHEST_MSG3: ' )',
    AUC_RESULT_MSG0: '誰も入札しませんでした。',
    AUC_RESULT_MSG1: ' が ',
    AUC_RESULT_MSG2: ' を',
    AUC_RESULT_MSG3: 'コインで落札しました!',
    CALCULATE_MSG1: 'あなたの手札から計算結果が ',
    CALCULATE_MSG2: ' になるようにカードを選択して、「解答」を押してください。',
    CALC_ERR_MSG1: '手札からカードを選択してください!',
    CALC_ERR_MSG2: '符号が末尾に置かれています!',
    CALC_RESULT_MSG0: '不正解です…! 再び解答するかパスをしてください。',
    CALC_RESULT_MSG1: '正解!! カードが１枚付与されます! 他のプレイヤーが解答するのを待っています…',
    CALC_FINISH_MSG0: '正解者は誰もいませんでした…',
    CALC_FINISH_MSG1: '正解者は ',
    CALC_FINISH_MSG2: ' です! ',
    CALC_FINISH_MSG3_1: 'に',
    CALC_FINISH_MSG3_2: 'コイン(カード枚数ボーナス: +',
    CALC_FINISH_MSG3_3: 'コイン）とカードが１枚配られました! ',
    PASS_TITLE: '本当にパスしますか？',
    PASS_MSG: 'パスする場合は「はい」を押してください。',
    ABILITY_TITLE: "本当に使用しますか？",
    ABILITY_MSG: "使用する場合は「はい」を押してください。",
    FIRED_ABILITY_MSG1: "が「",
    FIRED_ABILITY_MSG2: "」を発動した！",

}

export const Chinese = {
    // 言語
    LANGUAGE: 'Chinese',

    // ボタン・タグ
    PLAYER_NAME: '选手姓名',
    QUICK_MATCH: '与某人比赛',
    FRIEND_MATCH: '与朋友对战',
    LANG_EN: '英语',
    LANG_JP: '日语',
    LANG_CN: '中文',
    TUTORIAL: '教程',
    INTRODUCTION: '什么是 NumBuyer？',
    CAPTION: '游戏流程',
    TIME_LINE1: '直到比赛开始',
    TIME_LINE2: '卡片的分发和发布',
    TIME_LINE3: '拍卖',
    TIME_LINE4: '计算',
    TIME_LINE5: '游戏结束',
    CREATE_BTN: '做一个房间',
    JOIN_BTN: '加入房间',
    ROOM_ID: '房间号',
    ABILITY: '选择两个技能。',
    ABILITY_EXP1: "能力是可以在游戏中激活的特殊能力。有只能使用有限次数的主动技能和始终有效的被动技能。",
    ABILITY_EXP2: "有只能使用有限次数的主动技能和始终有效的被动技能。",
    BST_TYPE: '急速类型',
    ATK_TYPE: '攻击类型',
    RCV_TYPE: '恢复类型',
    JAM_TYPE: '干扰类型',
    CNF_TYPE: '混乱类型',
    LOBBY: '大堂',
    SETTING: '各种设置',
    MULTIPLICATION: '乘法',
    DIVISION: '除法',
    LIMIT: '数字上限',
    START_BTN: '开始',
    BACK_BTN: '出口',
    TARGET: '目标卡',
    AUCTION: '拍卖卡',
    BID_MSG: '请输入投标金额。',
    BID_BTN: '投标',
    SUCCESS_BID: '中标！',
    PASS_BTN: '不叫牌',
    ANSWER_BTN: '回答',
    ABILITY_TAG: '使用能力',
    YOUR_CARDS: '你的手',
    CALCULATE_FIELD: '计算字段',
    YES_BTN: '是的',
    NO_BTN: '不是',
    SUCCESS: '正确答案！',
    FAILED: '错误的答案…！',
    CONFIRM_BTN: '确认',
    TIME: '剩余时间',
    WIN_CONDITIONS: '胜利条件',
    WIN_MSG: '有',
    COIN: '硬币',
    RANKING: '排行',
    FINISH_BTN: '退出游戏',
    AGAIN_BTN: '再玩一遍',

    // チュートリアルメッセージ
    INTRODUCTION_MSG1: 'NumBuyer是一个由Number和Buyer两个字诞生的称号，顾名思义，它是一种将计算卡牌游戏与拍卖元素相结合的新型卡牌游戏。',
    INTRODUCTION_MSG2: '游戏规则',
    INTRODUCTION_MSG3: '首先，发两种类型的牌，数字和运算符。',
    INTRODUCTION_MSG4: '之后，将发布带有数字的“目标卡“。您可以跳过组合您必须制作“目标卡“数量的卡来赚取金币。',
    INTRODUCTION_MSG5: '第一个收集作为胜利条件的硬币数量的人就是这场比赛的获胜者！',
    INTRODUCTION_MSG6: '每回合会发一张牌，但仅凭这一点不足以构成“目标牌”的数量。因此，在“目标卡“发布后，「拍卖卡」将被发布。',
    INTRODUCTION_MSG7: '这张“拍卖卡“可以使用您的硬币以拍卖形式获得。',
    INTRODUCTION_MSG8: '让我们用好“拍卖牌“，为“目标牌”高效开牌吧！',
    INTRODUCTION_MSG9: '拍卖阶段结束后，进入计算阶段。让我们做一个计算公式，这样“目标卡“的数量就是你拥有的卡的计算结果。（当然，您只能使用与“目标卡“编号完全相同的一张卡）',
    INTRODUCTION_MSG10: '如果你能把“目标卡“的数字打出精彩，你将获得“目标卡“的价值和你使用的卡数的金币！（你将根据你使用的卡数获得奖励金币！)',
    INTRODUCTION_MSG11: '之后，让我们重复这一系列步骤，并以比任何人更快的速度收集大量硬币！',
    BEFORE_GAME_MSG1: "开始游戏",
    BEFORE_GAME_MSG2: "①您可以按此处更改为您喜欢的语言。",
    BEFORE_GAME_MSG3: "②输入您想在游戏中使用的玩家名称。",
    BEFORE_GAME_MSG4: "③如果您按“与某人对战”，您可以与来自世界各地的4个随机玩家对战。",
    BEFORE_GAME_MSG5: "④如果您按“与朋友对战”，您可以通过共享房间代码与熟人玩2-4名。",
    BEFORE_GAME_MSG6: "选择一个能力",
    BEFORE_GAME_MSG7: "①从五种能力中选择您要使用的两种能力。",
    BEFORE_GAME_MSG8: "②选择能力后，按“确定”进入下一个屏幕。",
    BEFORE_GAME_MSG9: "创建或进入房间（在“与朋友对战“的情况下）",
    BEFORE_GAME_MSG10: "①创建一个新房间来玩游戏。",
    BEFORE_GAME_MSG11: "②请房间创建者告诉您房间代码并输入房间代码。",
    BEFORE_GAME_MSG12: "③使用您输入的房间代码进入房间。",
    BEFORE_GAME_MSG13: "大厅（在“与朋友对战”的情况下）",
    BEFORE_GAME_MSG14: "显示房间中的参与者。（房间创建者旁边有一个图标）",
    BEFORE_GAME_MSG15: "①您可以按此处离开房间并返回标题屏幕。",
    BEFORE_GAME_MSG16: "②按此处复制此房间的房间代码。（告诉你想加入这个房间代码的朋友）",
    BEFORE_GAME_MSG17: "③当房间有2-4名时，房间创建者可以按这里开始游戏。",
    BEFORE_GAME_MSG18: "大厅（在“与某人比赛“的情况下）",
    BEFORE_GAME_MSG19: "显示房间中的参与者。",
    BEFORE_GAME_MSG20: "当房间里有４名参与者时，游戏开始。",
    DISTRIBUTION_MSG1: "开始游戏",
    DISTRIBUTION_MSG2: "①游戏的胜利条件写在这里。收集１００个硬币是本场比赛的获胜条件。",
    DISTRIBUTION_MSG3: "②您可以查看玩家信息。列出了玩家姓名、手中的牌张数以及您拥有的硬币。 （黄色背景是我的资料）",
    DISTRIBUTION_MSG4: "③你可以检查你的能力。您还可以跳过关注它来查看每个能力的描述。你看不到对手的能力。 （只能查看对方激活的时间）",
    DISTRIBUTION_MSG5: "手分配",
    DISTRIBUTION_MSG6: "①在这里，您将看到游戏情况的描述以及如何执行每个动作。",
    DISTRIBUTION_MSG7: "②首先，发两种类型的牌，数字和运算符。",
    DISTRIBUTION_MSG8: "释放目标卡",
    DISTRIBUTION_MSG9: "将发布带有数字的“目标卡”。您可以跳过组合双手并制作此数字来赚取硬币。",
    AUCTION_PHASE_MSG1: "拍卖卡的发布",
    AUCTION_PHASE_MSG2: "释放目标卡后，将释放拍卖卡。在此拍卖阶段，将为所有玩家举行一次拍卖，并将这张拍卖卡添加到中标者的手上。",
    AUCTION_PHASE_MSG3: "出价或拒绝",
    AUCTION_PHASE_MSG4: "①此处显示距离拍卖结束的剩余时间。当剩余时间为0时，该牌将授予当时出价最高的玩家。",
    AUCTION_PHASE_MSG5: "②您可以通过按“跳过”按钮在本回合拒绝拍卖。",
    AUCTION_PHASE_MSG6: "③按原样改写该数字，或按“+”按钮或“-”按钮设置投标金额。",
    AUCTION_PHASE_MSG7: "④您可以按“出价”按钮以设定的出价金额出价。",
    AUCTION_PHASE_MSG8: "当前最高出价",
    AUCTION_PHASE_MSG9: "当有人出价时，将显示当前的最高出价。您的出价不能低于最高出价。",
    AUCTION_PHASE_MSG10: "中标",
    AUCTION_PHASE_MSG11: "如果你中标，效果会像这样显示，中奖牌会加入你的手牌。",
    CALCULATION_PHASE_MSG1: "选择用于计算的卡",
    CALCULATION_PHASE_MSG2: "①选择手中的牌，以目标牌为计算结果。您不能连续选择数字卡。请务必插入密码卡。",
    CALCULATION_PHASE_MSG3: "②您可以通过按下“跳过”按钮来传递此回合的计算。",
    CALCULATION_PHASE_MSG4: "回答",
    CALCULATION_PHASE_MSG5: "按“回答”按钮并使用由所选卡片组成的公式回答。",
    CALCULATION_PHASE_MSG6: "错误的答案",
    CALCULATION_PHASE_MSG7: "如果答案不正确，用于答案的卡片将重新回到您的手上。您可以在规定时间内回答任意次数。",
    CALCULATION_PHASE_MSG8: "正确答案",
    CALCULATION_PHASE_MSG9: "如果您回答正确，您将获得目标卡的数量和用于答案的卡数量的硬币。用于回答的卡片将丢失。",
    CALCULATION_PHASE_MSG10: "重复上述“分发手牌”→“发布目标卡”→“发布拍卖卡”→“拍卖”→“回答”的步骤，继续游戏，使您拥有的硬币数量为中奖条件的数量。我会继续。",
    USE_ABILITIES_MSG1: "拥有能力",
    USE_ABILITIES_MSG2: "①您可以在右侧的玩家信息中查看您的能力，当您专注于它们时，将显示能力的效果。",
    USE_ABILITIES_MSG3: "②可以随时使用的主动能力，可以通过按下此处的按钮来激活。",
    USE_ABILITIES_MSG4: "使用主动技能",
    USE_ABILITIES_MSG5: "专注于按钮以查看技能的效果。您可以通过按下按钮来激活该能力。",
    USE_ABILITIES_MSG6: "调用能力",
    USE_ABILITIES_MSG7: "①当一个能力被激活时，会显示一条信息，说明谁激活了什么能力，它有什么效果。",
    USE_ABILITIES_MSG8: "②只有当能力被激活时，才会显示被激活玩家的能力。",
    USE_ABILITIES_MSG9: "激活被动技能",
    USE_ABILITIES_MSG10: "当满足效果中规定的某些条件时，被动能力会自动激活。",
    END_GAME_MSG1: "比赛的最终结果",
    END_GAME_MSG2: "①游戏的最终结果以排名格式显示。",
    END_GAME_MSG3: "②按此按钮退出房间并返回标题屏幕。",

    // エラーメッセージ
    NULL_NAME_ERR: '请输入你的名字。', // 名前が未入力
    SYMBOL_ERR: '您不能输入该字符。', // 禁止文字が入力されている
    NULL_ROOM_ID_ERR: '请输入房间号。', // ルームIDが未入力
    LENGTH_ROOM_ID_ERR: '请输入１０位数字的房间ID。', // ルームIDが10桁以外
    NOT_EXIST_ROOM_ERR: '此房间ID不存在。', // 存在しないルームID
    ABILITY_ERR: '选择两个技能。', // アビリティを2つ選択していない
    NULL_BID_ERR: '请输入金额。', // 金額が未入力
    NUM_ERR: '您只能输入数字。', // 数字以外が入力されている
    BID_ERR: '请输入高于最高出价的金额。', // 最高入札額以下の金額が入力されている
    LACK_ERR: "你没有足够的钱。", // 所持金が足りない
    DOUBLE_ERR: "您不能连续出价两次。", // ２回連続入札
    BAD_TIMING_ABILITY_AUC_ERR: "此能力不能在拍卖阶段使用。", // オークションフェーズに発動できないアビリティ
    NOT_MEET_ABILITY_3TURN_ERR: "该能力在游戏开始后的3回合内无法发动。", // 最初の3ターン発動できないアビリティ

    // ナビゲーションメッセージ
    QUICK_MSG: '当所有四个玩家在一起时，游戏将自动开始。',
    GIVE_CARD_MSG: '向玩家分发卡片…',
    SHOW_TAR_MSG: '目标卡是 ',
    SHOW_AUC_MSG: ' 被展出。',
    AUCTION_MSG1: '输入您的出价金额，选择出价 ',
    AUCTION_MSG2: ' 或跳过。',
    AUC_BID_MSG1: ' 出价 ',
    AUC_BID_MSG2: ' 硬币。',
    AUC_HIGHEST_MSG1: '当前最高出价: ',
    AUC_HIGHEST_MSG2: ' 硬币 ( ',
    AUC_HIGHEST_MSG3: ' )',
    AUC_RESULT_MSG0: '无人出价。',
    AUC_RESULT_MSG1: ' 用',
    AUC_RESULT_MSG2: ' 硬币中标了 ',
    AUC_RESULT_MSG3: ' !',
    CALCULATE_MSG1: '从你的手牌中选择一张牌，使计算结果为 ',
    CALCULATE_MSG2: ' ，然后按“回答“。',
    CALC_ERR_MSG1: '请从您的手牌中选择一张牌!',
    CALC_ERR_MSG2: '标志在最后!',
    CALC_RESULT_MSG0: '不正确…! 再次计算或跳过。',
    CALC_RESULT_MSG1: '正确!! 将赠送一张卡片! 请等待其他玩家…',
    CALC_FINISH_MSG0: '没有人给出正确答案…',
    CALC_FINISH_MSG1: '正确答案是 ',
    CALC_FINISH_MSG2: '! ',
    CALC_FINISH_MSG3_1: '将获得',
    CALC_FINISH_MSG3_2: ' 硬币(卡号红利 : ',
    CALC_FINISH_MSG3_3: ' 硬币)和一张卡片! ',
    PASS_TITLE: '你确定你不想出价吗？',
    PASS_MSG: '如果要跳过, 请按“是的“。',
    ABILITY_TITLE: "你真的会用吗？",
    ABILITY_MSG: "按“是的“使用",
    FIRED_ABILITY_MSG1: "激活“",
    FIRED_ABILITY_MSG2: "“!",
}